### ISSUE TITLE
hard to see, small fonts, visibility, use.

### ISSUE THREAD

**Issue by uptimestar** [coreybutler/fenix#100]
Hi,
Nice dev. sever for windows.
VERY hard to see. Ex:
https://www.dropbox.com/s/pxs298hdjt7tkvo/f.PNG

Notice VS Code to the left. The colors combo, small fonts and blur on Fenix. Menu icons as well.  On the image it looks a bit nicer than what I see, not sure why.
VERY HARD TO SEE/USE.

Can you re-visit your choices. I assume related to retina resolution on my Surface laptop.  You may have to borrow a retina display/laptop. Not sure what else it would be, but we need larger fonts, icons and whiter colors please.

**Comment by coreybutler** [comment]
We're working on it. See https://preview.fenixwebserver.com. The general release/Windows version should be available in a few weeks.

**Comment by uptimestar** [comment]
Yes command line would work assuming I can specify port and directory. And run a few 'instances' at a time or similar effect.
Still nicer UI would be good.

Nice web site. I wonder what did you create the web site in please?

**Comment by coreybutler** [comment]
There is an interactive UI on the preview site I mentioned... it's not just command line.

Click on
![image](https://user-images.githubusercontent.com/770982/37244536-295903a8-2450-11e8-982b-792dfd668ce8.png)

and you'll be able to navigate a mockup of the new UI:

![image](https://user-images.githubusercontent.com/770982/37244541-3dbc820c-2450-11e8-9ce3-60ec7561f1e8.png)

However; the preview is currently only available for macOS. We're still working on the installer for Windows.

The web page was written with the same technology we used to make Fenix 3.0.0. We use [Chassis](https://github.com/ngn-chassis) & [NGN](https://github.com/ngnjs) (we created both of them). Chassis is a CSS layout engine based that uses a responsive-typography strategy. NGN is our JS library. Both of these are currently open source, but we're still working on the documentation (and have not yet _officially_ released Chassis/NGN). I have briefly discussed what Chassis/NGN and other tools we've written (see [Developing Nirvana](https://www.youtube.com/watch?v=YdZv_4l4NMw)), but it's all high level stuff.

**Comment by coreybutler** [comment]
The website is just an example that you can play around with - the app is not full screen, but I can understand why someone would think that by looking at the website. 

The app can be resized however you like. Watch the video from my original response and you'll see I actually demonstrate how it responds to different size adjustments, themes, etc.

Thanks for the feedback. Can I ask which browser you were using to view the site? You should be able to click through the demo on everything back through IE11.

**Comment by uptimestar** [comment]
Chrome. I just clicked on demo and nothing happened. Yes, I would do on
website the small/ 'cute' screen example like you had in the older version.
