### ISSUE TITLE
Insufficient admin privileges

### ISSUE THREAD

**Issue by moodmap** [coreybutler/fenix#102]
When I try to set up a new web server and run it, I get an error telling me that I have insufficient admin privileges. I've tried opening Fenix as administrator but it didn't help.

**Comment by lostangelhf** [comment]
I'm having the same issue. Using 2.0.0. 
Also fenixwebserver.com could not be reached for me...

**Comment by 8thHalfHour** [comment]
Same issue here. Repeatedly.

**Comment by coreybutler** [comment]
Make sure you're operating your sites on a port above 1024.

**Comment by coreybutler** [comment]
V3 released: https://github.com/coreybutler/fenix/tree/3.0.0-rc.13
