### ISSUE TITLE
php files are downloaded

### ISSUE THREAD

**Issue by RKouchoo** [coreybutler/fenix#104]
If I use a tag like this which links to a php file which contains html
      ```<li style="float:right; border-left: 1px solid #bbb;" ><a class="active" href="../php/fb.php">dev</a></li>```

The php file is downloaded instead of opened by the browser..

**Comment by coreybutler** [comment]
Fenix is a static web server, so dynamic languages like PHP aren't supported in v2. We're working on a proxy for v3 (PRO edition) that will allow requests to be proxied to dynamic app servers (like PHP).
