### ISSUE TITLE
Get Fenix 3 - sever down since weeks

### ISSUE THREAD

**Issue by Acidham** [coreybutler/fenix#109]
Since weeks Fenix 3 preview is not downloadable form https://betaupdate.fenixwebserver.com/download 

Receiving error: 
```
Error 521 Ray ID: 4b19d6614ee7c27e • 2019-03-03 07:18:37 UTC
Web server is down
```

**Comment by nimohe** [comment]
me too.
```
Error 521
Ray ID: 4b34b9b03ba75041 • 2019-03-06 13:37:37 UTC
```

**Comment by coreybutler** [comment]
Crap. We changed servers in preparation for the general availability release and it looks like some things are not pointing to the right place. I'll get it sorted over the next few days as we roll out the release for both macOS and Windows.

**Comment by Acidham** [comment]
still connection timed out

> Error 522 Ray ID: 4ba69eae1867cc60 • 2019-03-20 09:22:38 UTC

**Comment by DaneTheory** [comment]
*bump* Still offline

**Comment by Mr-Sloth** [comment]
Still ^^

**Comment by DaneTheory** [comment]
_bump_ still offline.....

**Comment by WorkInProgress-Development** [comment]
_bump_ Still offline

**Comment by 8thHalfHour** [comment]
Confirming that it is still offline.

**Comment by coreybutler** [comment]
Instead of trying to fix this, we're prepping for general release. 

The only hold up is our code signing cert. We moved. Apple is still confirming the new address, then our certificate can be provisioned.

**Comment by JoshuaHolme** [comment]
Do you have a potential timeframe of release?

**Comment by coreybutler** [comment]
@JoshuaHolme now :-)

I just cut the first public release candidates for macOS and Windows, available at https://github.com/coreybutler/fenix/releases/tag/3.0.0-rc.13. These are 64-bit compatible.
