### ISSUE TITLE
Light theme for FWS 

### ISSUE THREAD

**Issue by mobilepadawan** [coreybutler/fenix#110]
Hi, I'm Fernando from Argentina.

I am a "_very happy user_" of **Fenix Web server**. I'm using it for testing purposes of many web samples, because I am writing a coding book. I use it to run the samples of the different exercises for the book, and I think a Light theme will be a great option for this application.

My book's editor forbade me taking screenshot of this app, because it's "complicated" for the printing process of the book pages. This will use much ink and the light words won't be legible for the reader.

Maybe my suggestion is very personal, but I think as a programmer that issue won't be complicated for the app coders.

Thank you very much for your time, and of course, for this great application.

**Comment by coreybutler** [comment]
Hi @mobilepadawan -

I think you would benefit from Fenix Web Server 3.0.0, which has a light and dark theme. You may also be interested in the new beta feature we call "Remote Imports", which allows developers to host web code on sites like github, github gists, bitbucket, and codepen (other users can import these directly into Fenix). You can see this at [docs.fenixwebserver.com](https://docs.fenixwebserver.com).

@gbdrummer is the UI engineer for Fenix 3. He can help you get the new version.

When your book is done, make sure to let us know. We'd be happy to tweet about it/spread the word, or even share a blog article about your experience with Fenix (if you're interested).

**Comment by coreybutler** [comment]
@mobilepadawan - it's probably too late, but the new version of Fenix is available and it has a light theme. It's available for macOS and Windows, available at https://github.com/coreybutler/fenix/releases/tag/3.0.0-rc.13

![image](https://user-images.githubusercontent.com/770982/65363225-50fdc680-dbd0-11e9-8e1f-65dbb70fc957.png)
