### ISSUE TITLE
hidden dot files don't serve

### ISSUE THREAD

**Issue by chriscortopassi** [coreybutler/fenix#111]
I like Fenix but I can't use it because I need to serve hidden files whose names start with period (.) for example

http://192.168.0.6/apps/hello/.app.cfg

no problem with nginx

**Comment by coreybutler** [comment]
This was a known issue in Fenix 2. It has been corrected in Fenix 3, but we don't plan to produce any further updates for Fenix 2. Fenix 3 will be released soon. If you need Fenix 3 now, @gbdrummer can send you a copy for macOS. I will not be able to provide a Windows version for at least a week or two (I am in the middle of a move).

**Comment by coreybutler** [comment]
Closing the issue, but feel free to let me/@gbdrummer know which operating system you would need for Fenix 3.

**Comment by chriscortopassi** [comment]
@coreybutler @gbdrummer I need Windows please

**Comment by chriscortopassi** [comment]
@coreybutler @gbdrummer any ETA on a Windows Fenix 3?
