### ISSUE TITLE
Alert while opening Fenix

### ISSUE THREAD

**Issue by vigneshrajarr** [coreybutler/fenix#114]
Downloaded version 2.0.0 for Mac
While opening, it shows the following alert.
“Fenix” needs to be updated. The developer of this app needs to update it to work with this version of macOS. Contact the developer for more information.

I am using Catalina v10.15.1

**Comment by coreybutler** [comment]
Fenix 2 has been retired. Use Fenix 3.0.0 instead. 

Download at https://preview.fenixwebserver.com. 
Docs available at https://docs.fenixwebserver.com.
