### ISSUE TITLE
Question about Fenix capacity

### ISSUE THREAD

**Issue by jhoski** [coreybutler/fenix#120]
I have a slightly different use case for Fenix. We have a timing and scoring system for our racing events that publish a web site with static pages to a directory on the Windows computer where the software runs. Most users of the system push the site to someplace that has public access, however, that is complicated and prone to failures.  After seeing Finix and Localtunnel in action I was wondering if that would be a more efficient way to see the site. The events last for a day and there would be, on average 100 connections and perhaps occasionally up to 200. The laptop is a good i7 4 core with 16GB memory. My question is would Finix and Localtunnel support that many connections? Thanks, Jay Hoskins, Sports Car Club of Rockford.

**Comment by coreybutler** [comment]
Fenix would easily support that number of viewers (and many more). However; localtunnel.me (3rd party) can be unreliable. Fenix v3 has a built in mechanism to reconnect if a connection is broken, but localtunnel doesn't guarantee the same address will be reassigned.

If your circumstance allows it, you can access the laptop directly via IP address, i.e. http://192.168.0.x:port. That would provide a more reliable connection.

**Comment by jhoski** [comment]
OK, thanks for the quick response. Our alternative is to use a local network with high power outdoor wifi access points, but, as you can imagine that is a bit more infrastructure. I will try Fenix out and send something your way if we settle on it. Thanks again. Jay

**Comment by coreybutler** [comment]
Closing due to age.
