### ISSUE TITLE
htaccess

### ISSUE THREAD

**Issue by azadatarr** [coreybutler/fenix#126]
Hello I installed fenix 3.0 for macos.

However, I was using htaccess for the route before, I couldn't find how to do it for fenix.

Example of my htaccess usage;

Options +FollowSymLinks
RewriteEngine On
RewriteRule ^login$ login.html [L]
RewriteRule ^dashboard$ index.html [L]

**Comment by coreybutler** [comment]
htaccess is not supported. That's primarily an Apache server concept, which blends web servers with a router.
