### ISSUE TITLE
Full Screen Loses Windows

### ISSUE THREAD

**Issue by calendee** [coreybutler/fenix#41]
Demonstration:

- Launch the Fenix app
- Click the Full Screen shortcut.  All is good.
- Cmd-Tab to another app
- Cmd-Tab back to Fenix
- Fenix shows no open windows.

To recover, I have to try the Window->Fenix Web Servers option at least once, sometimes twice.

What Should Happen
- When switching back to Fenix, the last active window should be viewable.

Platform : Mac OS X 10.9.3
Fenix : 2.0.0

**Comment by coreybutler** [comment]
Fixed in 3.0.0.
