### ISSUE TITLE
button enable public view not functional / request browser time out

### ISSUE THREAD

**Issue by jnschw** [coreybutler/fenix#51]
windows 7 pro; behind company firewall/proxy

no reaction on button, i.e.connection to localhost.me does not start at all.

request browser connects to localhost with ie, not with firefox, in both cases status bar stays yellow with error message "remote server timed out"

maybe a problem with proxy settings, same installation at home without any problems.
please provide enhanced error handling/msg

**Comment by coreybutler** [comment]
I'm closing this because it will not be added to Fenix 3. Instead, we are separating the request browser into it's own application, tentatively called Inbound. This issue has been added to our to-do list for that app.
