### ISSUE TITLE
Unable to execute file: C:\ProgramData\Fenix\fenix.exe

### ISSUE THREAD

**Issue by IGitSylvia** [coreybutler/fenix#53]
---

-SETUP-

X Unable to execute file:
C:\ProgramData\Fenix\fenix.exe

CreateProcess failed; code 2.
They system cannot find the file specified.

```
                            - OK - 
```

---

**Comment by murone** [comment]
Same issue. I'm on Windows 10 and have tried multiple compatibility modes per Issue #52 
Suggestions?

**Comment by coreybutler** [comment]
I can't recreate this issue, so I'm confident it has to do with the local environment. I'm 99% sure it has to do with permissions.... the question is "which directory don't I have proper permissions on?"

To troubleshoot, I would run the Fenix installer, but don't close it on the final screen. Instead, look through your temporary files directory. I would search for the word "fenix" and I would also sort through the files by size.... at this point in the installation, the file could be anywhere from 25MB to 45MB. If you can't find the file, then it's likely the installer didn't have permission to write to the temporary files directory. If you do find it, the installer probably didn't have permissions to copy the directory to your final installation path (that you specified in the installation process).

Another thing to consider is whether you're behind a proxy. Fenix 2 downloads the node-webkit binary during the installation process. If a proxy or firewall is blocking that, the file will never be made.

**Comment by murone** [comment]
You're probably right on the proxy thing. I did try installing on public internet, but I think I probably still had my windows, node, bash, and git proxies configured for being on network. I'll try fixing that first and then if that doesn't work I'll check out temp permissions, but doubt it's that as I'm full local admin on my PC.

**Comment by Nicknack1234** [comment]
Same issue, No proxy just vanilla windows 10. If you dont run as administrator, It doesnt download additional files, or install drivers. Installer just proceeds without reporting any problems. You end up with a missing exe file.

**Comment by coreybutler** [comment]
At this point, I doubt I'll try to fix this for Fenix 2. Installer issues are notoriously time consuming. Recreating this issue (which I still can't) and fixing it will take longer than it will to finish Fenix 3 for Windows. The Fenix 3 installer will ship everything (no extra downloads), including an autoupdate feature, so this problem should go away. I don't have an exact ETA on the Fenix 3 Windows release, but we are done with the Mac version and prepping for release.... so it shouldn't be too long.

I'm (hesitantly) going to close this on the premise that Fenix 3 will be the upcoming solution.
