### ISSUE TITLE
Make markdown parsing an option

### ISSUE THREAD

**Issue by BrynM** [coreybutler/fenix#61]
Recently I needed to test reading some markdown files in JS over HTTP. I had to manually comment out the `else if` condition at https://github.com/coreybutler/fenix/blob/7a361dc590e59ff0ce27db1702ca6cf154b060c6/src/lib/api/server.js#L482 to make it work.

Would be nice to have a config flag or option to turn off markdown parsing for individual servers. Sometimes parsing is handy, sometimes it's not.

**Comment by coreybutler** [comment]
Yeah, I had this issue too. Markdown rendering will be optional in the next version.

**Comment by BrynM** [comment]
Sweet! Thanks!

**Comment by coreybutler** [comment]
Closing this since it's been added to Fenix 3.

![image](https://cloud.githubusercontent.com/assets/770982/17311560/e413611e-5811-11e6-83c0-48e91b3e52d1.png)
