### ISSUE TITLE
Web Directory Full Path Disclosure

### ISSUE THREAD

**Issue by ebrinkster** [coreybutler/fenix#62]
Minor issue, since this is obviously a development tool for collaboration between multiple parties.  Modern browsers will typically attempt to find a favicon.ico file when browsing a website.

The HTTP response returns "ENOENT, stat C:\path\to\where\the\webserver\files\are' -- Don't know much about Node, but appears to be a code for 'file not found'.  Generally speaking, you never want web servers to leak the full path of where files are hosted.  Not an 'issue' per-se due to the nature of the program, but just wanted to post in case this is of interest.

Screenshots below:
![request](https://cloud.githubusercontent.com/assets/616045/10555564/acda47e0-7436-11e5-996d-5a485462a377.PNG)
![response](https://cloud.githubusercontent.com/assets/616045/10555563/acd9679e-7436-11e5-9dfa-b27f2114b6b4.PNG)

**Comment by coreybutler** [comment]
Noted!

**Comment by coreybutler** [comment]
Fenix 3 has custom errors now to prevent the stack from being exposed. We've also switched from Express to Koa for general web serving, so this issue should never come up again.
