### ISSUE TITLE
Cannot start server, path gets lost

### ISSUE THREAD

**Issue by danielnieto** [coreybutler/fenix#63]
This is a funny/weird/annoying thing, I do NOT know how to reproduce this but once in a while (very frequently) a server path gets lost. It just says [object Object], and the indicator instead of green or red it is yellow:

![image](https://cloud.githubusercontent.com/assets/2120107/13574692/e226c1b0-e44a-11e5-81a4-6b4119d482d6.png)

in this case, the two bottom servers are in this "limbo state", when I try to edit them this is what I see:

![image](https://cloud.githubusercontent.com/assets/2120107/13574736/0fd52700-e44b-11e5-99e8-17e51ec77f0b.png)

Then if I click on the folder icon, and I select again the folder of the server (which always existed and hasn't changed location or anything) and then I click on Update, the "Play" button won't show again, and the indicator is still yellow:

![image](https://cloud.githubusercontent.com/assets/2120107/13574836/8f23bcd8-e44b-11e5-9d8a-93995ffd7da3.png)

To fix this, once I re-select the folder, and click update, I need to restart Fenix, and then it would be fixed... until it happens again soon... 

I can confirm that this issue happens frequently and occurs on both Windows and Mac, so this is not an OS specific bug. I'm surprised no one has reported this issue yet, since it happens quite a lot, I've been using Fenix every day for the last 8+ months, and this bug happens at least once a week.

I must say that since I use it everyday, I never stop the servers before closing Fenix, sometimes I don't even close Fenix, I just put the laptop to sleep, I'm not sure if this is something that can trigger the bug.

**Comment by coreybutler** [comment]
I have actually been noticing this recently too, but I attributed it to the fact I'm running the development version of Fenix alongside the latest release. Thank you for reporting this.

I only notice this issue when my computer goes to sleep, so I suspect the change in network state is causing a rewrite of the file that saves the server configurations. It's definitely stringifying an object and writing that to the file.

I should have time to look into this over the weekend to assess what it will take to fix. Depending on complexity; it might be faster to just wait until the next release where data management has been completely rewritten with NGN/Chassis (projects I've been working on for a few years). However; if it doesn't require too much time, I'll release a patch.

**Comment by coreybutler** [comment]
So I got side tracked from patching this in Fenix 2, but it has been addressed in Fenix 3 (due out in the next few weeks). I'm going to close this as a "won't fix" since it has been addressed in v3.0.0.
