### ISSUE TITLE
Server close after few minute

### ISSUE THREAD

**Issue by JanMolendijk** [coreybutler/fenix#66]
How come Fenix close the local-tunnel after few minutes ?

**Comment by coreybutler** [comment]
Fenix doesn't close the tunnel... but the remote host (localtunnel.me) sometimes disconnects after a period of inactivity. How long that period is seems to vary. In Fenix 3 (what I'm working on now), I've added a keepalive function to work around this. So far, I've been able to keep a server shared for about 9 hours without a disconnection. We're also experimenting with our own dedicated tunneling service (commercial version) for a more consistent experience.

**Comment by coreybutler** [comment]
P.S. Please use gitter for questions.
