### ISSUE TITLE
localtunnel.me (adress)

### ISSUE THREAD

**Issue by JanMolendijk** [coreybutler/fenix#67]
Dear Corey Butler,

First off all: Thanks for responding quickly into the last question i had...

I have another question is it posibble into the new version to make one localtunnel-adress
so I have to share only one local-tunnel adress also after closing the server ?

**Comment by coreybutler** [comment]
There's no way to guarantee you'll always get the same address from localtunnel.me (that's a 3rd party). Fenix 3.0.0 attempts to get the same address each time, but it's not always granted by the localtunnel.me servers. Guaranteed addresses and dedicated tunneling servers are something we're working on for the Fenix Team edition (paid).

**Comment by JanMolendijk** [comment]
When do you think your team is ready for Fenix 3.0.0 + Fenix Team edition ?

**Comment by coreybutler** [comment]
We haven't set a specific release timeline, but we're working hard to get the open core version of Fenix 3 launched within the next few weeks. We're hoping to get the team edition launched later this year.
