### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by terriblespider** [coreybutler/fenix#68]
Is Linux support planed for the future?

**Comment by coreybutler** [comment]
Not officially. Unfortunately, there just isn't enough demand to warrant how much extra effort would go into it. Despite node-webkit/NW.js/electron being "Cross Platform", there are a large number of edge cases ranging from tray menus to trustchains and many things in between.

That said, Fenix 2.0 will _most likely_ run on Linux. There are [instructions](https://github.com/coreybutler/fenix/wiki/Running-on-Linux) for how to get started.

**Comment by terriblespider** [comment]
Okay, thanks :) I'll give it a try ;)
