### ISSUE TITLE
Fenix hangs while loading

### ISSUE THREAD

**Issue by andyste1** [coreybutler/fenix#69]
Installed earlier in the week and had been using it fine. I had used it this morning and closed it down. I tried to open Fenix a short time later and it now hangs on startup. The splash screen appears and a few seconds later the animated coloured blocks stop moving. I have to end task to get rid of Fenix. Have tried restarting the PC but makes no difference.

**Comment by coreybutler** [comment]
Which operating system are you running it on?

**Comment by aprilsweetie** [comment]
I'm having the same problem here. I use OS X EL Capitan. It works fine before today. This morning I tried to edit one server, but after clicked save, it stopped responding, so I quit Fenix and tried to reopen it. Now Fenix just hangs on startup, with three dots spinning. In Activity Monitor, I see there are two node-webkit helper under Fenix.
 I tried to install Fenix in terminal, after installed, type in fenix list, it said "Fenix is not currently running or could not be reached." 
Can you please help?

**Comment by coreybutler** [comment]
@aprilsweetie - On OSX, remember you have to right click on the icon to actually close apps. It sounds like you're attempting to run two instances of Fenix at the same time (which it won't allow). 

I'm not sure why it's hanging (unless you're using OpenUI which has a known bug), but you can always force it to close.

As for the terminal, the command line tool is a separate. It sounds like you haven't installed it. Please visit [fenixwebserver.com](http://fenixwebserver.com/) and scroll down to the section called "Command & Conquer". There are also YouTube videos linked from the website (though the command line one has terrible audio).

**Comment by coreybutler** [comment]
@andyste1 - I forgot to mention... I know you're running Windows, but I need to know which version (7/8/10, etc).

**Comment by coreybutler** [comment]
Closing as abandoned.
