### ISSUE TITLE
Using Fenix to share an USB embedded website

### ISSUE THREAD

**Issue by Sephi-Chan** [coreybutler/fenix#71]
Hello,

I have a single page application (using React) that fetches data from a json file (data.json) that acts as a database. The directory structure is like :

```
MyApp
├── Fenix.app // For Mac users.
├── Fenix.exe // For Windows users.
├── app.js
├── data.json
├── index.html
└── react.js
```

My goal is to share it with my colleagues (teachers with nearly no skill with computers), so they can use it like it:

- They put the website in their USB drive (so they can bring it anywhere, offline) ;
- They operate on it (set student marks and so on) ;
- They save their changes: the download of a new data.json is prompted to replace the existing one.

I would like to embed the minimal configuration so they really have nothing more to do than executing Fenix.exe.

I can't do it now since they need to create the server in Fenix before running it. Would it be possible to embed such configuration?

Thanks!

**Comment by coreybutler** [comment]
As much as I like promoting Fenix, this probably isn't a good case for it. Personally, I'd setup a small [Electron](https://electron.atom.io) app, which is better for distribution. You could embed the same web server from the Fenix code, or use something like ExpressJS.

If you really, really want to use Fenix, then I would suggest looking into the API, which is documented in the wiki. You can use it to programmatically launch a web server for your users. Again though, I think Electron or NW.js are a better fit for your audience.

**Comment by Sephi-Chan** [comment]
Thanks @coreybutler i'll read about Electron. Good luck with Fenix!
