### ISSUE TITLE
doesn't seem to traverse directories begging with a dot

### ISSUE THREAD

**Issue by orionshock** [coreybutler/fenix#72]
while it is true that windows really hates the folders with a dot at the start, it seems to also affect the program. 

For example this doesn't work at all:

http://127.0.0.1/.well-known/acme-challenge/

**Comment by coreybutler** [comment]
Hmm, I don't have a problem with dot notation on Windows. Are you certain this is a problem reading the directory?

The pattern you're using suggests you're trying to do a LetsEncrypt webroot validation. Please note that LetsEncrypt does not work on a local IP address like 127.0.0.1, nor does it work with localhost. LetsEncrypt only works with domain names. Furthermore, Fenix 2.0 does not support SSL. Fenix 3.0, which hasn't been officially released yet, has a commercial (paid) plugin that supports SSL/TLS.

**Comment by orionshock** [comment]
Ah, 
upon further double-checking i found that i had pointed the web root to the wrong folder altogether. 
once i had it starting in the right place, it worked like a charm :) 
sorry, false flag here..

**Comment by coreybutler** [comment]
Sounds like alot of effort! Glad you got it working.
