### ISSUE TITLE
Can't close 'help' window on macOS

### ISSUE THREAD

**Issue by ajmas** [coreybutler/fenix#76]
I clicked on the help menu, but now I can't close the windows which appeared. No close button or obvious way to close the window. While command-W will close it, that isn't obvious.

Would suggest having a close button of some sort.

Using macOS 10.12.3 and Fenix 2.0.0

**Comment by coreybutler** [comment]
There is an X to close the help window in the upper right corner. If you're
not seeing that, perhaps you could take a screenshot and post it here?

**Comment by ajmas** [comment]
I see it now. It is hard to see if there isn't enough contrast on the screen.

Screen shot attached.

![screen shot 2017-03-08 at 22 50 26](https://cloud.githubusercontent.com/assets/682269/23735118/c1e0d260-0451-11e7-8445-0588f035dafb.png)

**Comment by coreybutler** [comment]
The next version has light and dark modes with much starker contrast. Here's a screenshot to demonstrate the light theme:

![Image](https://scontent-dft4-2.xx.fbcdn.net/v/t31.0-8/15776709_343601442692108_6860209546777873317_o.png?oh=d312920405d1b7a3766064f6908e18b1&oe=5930E1AD)
