### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by danielsmy** [coreybutler/fenix#79]
I am getting this message when starting the server.
![screenshot_6](https://cloud.githubusercontent.com/assets/26442599/25297061/6e8c5c9e-26a0-11e7-8d58-c70faae7023e.png)

**Comment by coreybutler** [comment]
Hmmm... `getExtension` isn't used in the fenix core code. It may be in one of the older dependencies (like Zepto), but this is the first I've seen of this issue... does this occur when you are opening Fenix or just launching a specific server?

**Comment by danielsmy** [comment]
I've created and deleted 2 servers that both have this error. However, it doesn't seem to effect the operation of the application.

**Comment by coreybutler** [comment]
Which operating system are you using? Which locale (is it non-English)? Are there any special characters in the path to your webroots?

**Comment by coreybutler** [comment]
Closing due to age/non-response.
