### ISSUE TITLE
Fenix keeps downloading my PHP files

### ISSUE THREAD

**Issue by Nmoleo64** [coreybutler/fenix#80]
If I have a PHP file on the server, it is getting downloaded instead of being displayed. How can I fix this?

**Comment by coreybutler** [comment]
This is expected behavior for a static web server. Please see the wiki entry called [Does Fenix support my favorite language or database?](https://github.com/coreybutler/fenix/wiki/faq#does-fenix-support-my-favorite-language-or-my-favorite-database-ie-php-net-mysql-etc).
