### ISSUE TITLE
mySQL question 

### ISSUE THREAD

**Issue by Dani-Ivanov** [coreybutler/fenix#81]
Hello,

I wanted to ask if there is a way of adding some.js file at the server side which can handle mysql db connection ?

**Comment by coreybutler** [comment]
No, Fenix is static-only. We don't plan on adding anything to Fenix to support this either. However; I'm working on another application, code-named "Inbound", which will have some dynamic server capabilities and may be able to support database connections. However; it's only an early-phase prototype at the moment, so it probably won't be ready for users until the end of the year or early 2018.
