### ISSUE TITLE
Deceptive Website Warning

### ISSUE THREAD

**Issue by manngo** [coreybutler/fenix#82]
I have only discovered this product today, and downloaded it with impunity on my Mac this morning.

Now I find that the download link on the website leads to a Deceptive Website Warning, for both the Mac and the Windows version. It seems to be OK if I download it directly from GItHub

**Comment by coreybutler** [comment]
Wow, thanks for bringing my attention to this. I was unaware of this until now.

**Comment by coreybutler** [comment]
Resolved with 2848d112188c89b10c2264e85c6f3d8c3828645c.

Thanks again @manngo!
