### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by GlobalKST** [coreybutler/fenix#83]
Hi Guys,

is it possible to use a .htaccess file in combination with Fenix? 

Cheers KST

**Comment by coreybutler** [comment]
Not in the current version. We're about to unveil Fenix 3 (free edition), which won't have this either, but the entry-level paid app (coming later this year) will have a basic authentication system. Using a `.htaccess` file wasn't specifically in the roadmap (the new security system is a bit more dynamic), but adding support for that would certainly be possible if there is interest.
