### ISSUE TITLE
Make it possible to create HTTPS servers without the tunnel.me proxy. 

### ISSUE THREAD

**Issue by Warix3** [coreybutler/fenix#85]
It would be great if we could create not only HTTP but also HTTPS servers without the builtin proxy. We just add our cert file and that's it.

**Comment by coreybutler** [comment]
This is already built into Fenix 3 PRO (paid edition). See the note in the README about it for details. The free version of 3 is being released now (in waves) and should be generally available within the next 2-3 weeks. We're on track to release the PRO edition at the end of the year.
