### ISSUE TITLE
Is exist Offline Installer or portable version?

### ISSUE THREAD

**Issue by Ozymandias1** [coreybutler/fenix#88]
Is exist Offline Installer or portable version?

**Comment by coreybutler** [comment]
No for Fenix 2.0. Yes for Fenix 3.0. 

Fenix 3 is currently in the final developer preview for macOS (see preview.fenixwebserver.com) and I've almost completed the Windows offline installer (hopefully releasing it early next week). The Fenix 3 general release will likely be on or around November 1.

**Comment by Ozymandias1** [comment]
i got it, thanks.
