### ISSUE TITLE
Install Stop working

### ISSUE THREAD

**Issue by mahdi-gh1373** [coreybutler/fenix#90]
my file stop working during install what should i do ?

**Comment by coreybutler** [comment]
Are you trying to use Fenix 2 or Fenix 3? What operating system are you using? Are you behind a proxy?

**Comment by mahdi-gh1373** [comment]
Itry to install Fenix 2.0.0 from it's site and I'm on windows.I don't have any proxy.

**Comment by coreybutler** [comment]
I'm not sure what's wrong, but if the installation is interrupted, it will cause the behavior you're experiencing. The installer downloads an NW.js, so the only place I can think of where an interruption would occur is during the download process.
