### ISSUE TITLE
Stop and Start VIA command line

### ISSUE THREAD

**Issue by matrixebiz** [coreybutler/fenix#95]
Hello, if I detect that Fenix is hanging or having issues, How can I restart it (Stop/Start) via Windows (dos) command line? I have a program already that starts programs automatically when they crash so should I just do a "taskkill /F /IM fenix.exe" or does fenix have some command line options to do this automatically? Thank you

**Comment by coreybutler** [comment]
https://github.com/coreybutler/fenix-cli
