### ISSUE TITLE
Fenix CLI on Windows

### ISSUE THREAD

**Issue by matrixebiz** [coreybutler/fenix#96]
Hello, I would like to check out Fenix CLI so I can use some of the fenix command line options but I do not know how to install this in Windows. I tried just running "Fenix List" to check and see if the command line options were already implemented in the Windows version but nothing happened so just looking for some help please. Thanks

BTW - Seems like a great Webserver, better than Apache for my usage :) Thank you for creating it.

**Comment by coreybutler** [comment]
The command is `npm install -g fenix-cli` (this is a node app). There is a series of getting started videos at https://www.youtube.com/playlist?list=PL6u9ibuk0pbM68hZONUq-vY39ByaXoJj- and the [website](http://fenixwebserver.com) has additional details.

Just so you know, Fenix 3 (a new version) is complete, but it is only available for Mac at the moment. We've working on the installer (a complex process). Unlike Fenix 2, Fenix 3 has the command line utility built in. You can see a preview at https://preview.fenixwebserver.com.

**Comment by matrixebiz** [comment]
Okay, awesome, I can just wait then for the new windows version. I'll sign up for the Newsletter. Thank you

**Comment by matrixebiz** [comment]
Hello, any ETA on version 3 for Windows? Thanks

**Comment by coreybutler** [comment]
It will be after Christmas, possibly the first week of January. The necessary changes in the underlying libraries we're using for the installation platform will be ready by Dec 25... so once we integrate them, we'll release the developer preview. The GA release usually follows 2-3 weeks later (after a feedback period).

**Comment by coreybutler** [comment]
If you're on the mailing list, you'll receive a link to download the preview version for Windows when it's ready.

**Comment by KioMioLLC** [comment]
Any update on Fenix 3 for windows release date?

**Comment by coreybutler** [comment]
@KioMioLLC We've been going through a big transition that held up work on the Windows installer... but it's a good transition. We should have full time efforts focused on building Author.io (the parent of Fenix) soon.... so it's no longer just a side project. I'm hopeful to see a formal release at the end of March or during SXSW.

**Comment by KioMioLLC** [comment]
Wonderful! Thank you and good luck. It is a great product.

**Comment by coreybutler** [comment]
Closing now that Fenix 3 is available for both macOS and Windows. The new version has a new native CLI utility. We made every effort we could to provide a smooth transition. The new version of the app attempts to help migrate, but there is also a migration tool at http://migrate.fenixwebserver.com.
