### ISSUE TITLE
Feature Request : custom CSS when serving markdown

### ISSUE THREAD

**Issue by mrec** [coreybutler/fenix#97]
Currently it looks like Fenix just injects

    <style>BODY{font-family:Arial,sans-serif;}</style>

at the start of the HTML, which is a bit spartan. Could it check for a specifically-named CSS file like `_fenix_md.css`  in the server's root directory, and inject that instead?

**Comment by mrec** [comment]
Whoops, apologies, looks like [this is already coming in Fenix 3](https://docs.fenixwebserver.com/preferences.html#markdown-rendering-custom-stylesheet). Closing.

**Comment by coreybutler** [comment]
Yup, and if you're a Mac user, you can try it out by downloading at https://preview.fenixwebserver.com. The Windows installer has been quite challenging, but it's almost done too.
